DROP TABLE IF EXISTS todo;

CREATE TABLE todo (
    id TEXT PRIMARY KEY,
    server TEXT NOT NULL,
    username TEXT NOT NULL,
    color TEXT NOT NULL,
    task TEXT NOT NULL,
    done BOOL NOT NULL DEFAULT FALSE
);
